### ISSUE TITLE
Poisoned `then` property rejecting the returned promise

### ISSUE THREAD

**Issue by leobalter** [es-shims/Promise.allSettled#1]
Ref https://github.com/tc39/proposal-promise-allSettled/issues/41

This shim needs a fix one way or another after the outcome of the issue ref'ed above.

For the current specs it needs to at least reject the returned promise.

Example:

https://gist.github.com/leobalter/d5ddfd403c0b92333201ea7f8872d5a4#file-using-shim-js

**Comment by ljharb** [comment]
Seems like the resolution was that it should reject the resulting promise, and not resolve it with a settled reason object for it.

**Comment by leobalter** [comment]
Which matches the current tests on Test262.
