### ISSUE TITLE
Throwing an error make rejected promises return empty reason

### ISSUE THREAD

**Issue by olegario96** [es-shims/Promise.allSettled#10]
Hi, I have the following code inside a function that returns a promise:
```typescript
throw new Error("couldn't resolve submission");
```

And then a I have as well:
```typescript
const results = await promiseAllSettled(externalResponsePromises);
```

But whein I log the `results` const I got:
```typescript
[{"status":"rejected","reason":{}}]
```

Why I'm not seeing the error described in the `reason` object?

**Comment by ljharb** [comment]
Are you sure you’re not? Errors don’t have any enumerable properties, and some console.log implementations don’t give helpful output in nested objects. What if you log `results.reason`, or `String(results.reason)`?

**Comment by olegario96** [comment]
@ljharb I'm using:

```typescript
console.log(JSON.stringify(results));
```

**Comment by olegario96** [comment]
Am I missing something?

**Comment by ljharb** [comment]
No, that's correct - JSON.stringify is not a faithful representation of JS objects, including error objects. Try just `console.log(results)`.

**Comment by olegario96** [comment]
`JSON.stringify` should be banned from mankind 🤦‍♂

**Comment by olegario96** [comment]
Btw, thanks for the assistance
