### ISSUE TITLE
What's the purpose of this `try..catch`?

### ISSUE THREAD

**Issue by getify** [es-shims/Promise.allSettled#13]
Just was peeking at the implementation, and ran across a `try..catch` that was curious to me:

https://github.com/es-shims/Promise.allSettled/blob/master/implementation.js#L30-L34

Wondering if you could explain in what scenario the `itemPromise.then(..)` call could synchronously throw, since you're passing two known-valid functions (that you created) to it?

**Comment by ljharb** [comment]
If Promise.prototype.then is overwritten, or if PromiseResolve results in a Promise subclass that has its own then impl, then i can’t rely on it never throwing.

I could probably check that itemPromise.then is === the intrinsic, and use Call if so, and try/catch Call if not, but that’s unlikely to be a perf win in aggregate.

**Comment by getify** [comment]
got it, should have realized that, thanks. :)
