### ISSUE TITLE
What is the baseline requirement for use in Node v11?

### ISSUE THREAD

**Issue by ChrisMiami** [es-shims/Promise.allSettled#15]
So, I assumed that the "Typical Usage" example was supposed to be comprehensive, and that not all lines of it are required to use the function `allSettled()`.  From that example, I did this:
```
    var pas = require('promise.allsettled');
    pas.shim();

    Promise.allSettled(listeners).then(()=> {
      res.status(200).send(JSON.stringify(this.putResults));
    }).catch( err => {
      wslog.warn(`POST request for ${this.filename} failed, at least in part: ${err}`)
      res.status(200).send(JSON.stringify(this.putResults));
    });
```
But I'm still getting `TypeError: Promise.allSettled is not a function`.  Do I need to use all those lines just to patch Promise?  Seems overkill...  I *only* added `promise.allsettled` from NPM.

**Comment by ljharb** [comment]
The smallest possible line you need is `require('promise.allsettled/auto')` (the `pas.shim()` stuff works too, it's just longer and loads slightly more code).

That code should absolutely work in node v11 - in my node 11 repl, `require('promise.allsettled/auto'); typeof Promise.allSettled` returns `'function'`.

**Comment by ljharb** [comment]
I'm going to close this; but if in fact there's a bug I'm very interested in addressing it, so I'll be happy to reopen if there's more information to be had.

**Comment by ChrisMiami** [comment]
Hey Jordan,

Not sure why the code didn’t work on my instance of Node. I’ll try the modification you sent and am also willing to try any other experiments that’d help you.

Chris

**Comment by ljharb** [comment]
If you still can't get it to work, a repro repository or codesandbox link would help immensely.
