### ISSUE TITLE
version 1.0.2 breaks webpack: 'return' outside of function

### ISSUE THREAD

**Issue by zaggino** [es-shims/Promise.allSettled#7]
Using `1.0.1` works but `1.0.2` breaks webpack build with:

```
Creating an optimized production build...
Failed to compile.

./node_modules/is-map/index.js
SyntaxError: /usr/app/node_modules/is-map/index.js: 'return' outside of function (12:1)

  10 | \t\treturn false;
  11 | \t};
> 12 | \treturn;
     | \t^
  13 | }
  14 | 
  15 | var $mapHas = $Map ? Map.prototype.has : null;
```

**Comment by ljharb** [comment]
Top-level return has always been valid in node CJS modules. Webpack v4.31+ should have support for this pattern; what version are you using?

**Comment by ljharb** [comment]
v2.0.1 of both is-map and is-set have been released.

**Comment by zaggino** [comment]
@ljharb we're using create-react-app, version is `react-scripts@3.3.0` which references webpack `4.41.2` https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L79

**Comment by ljharb** [comment]
@zaggino in CRA's case, the problem is caused by two things: 1) transpiling node_modules, which is highly unsafe, and 2) babel does not enable the `allowTopLevelReturn` by default, nor does CRA enable it, which makes transpiling all valid CJS modules impossible.
